apiVersion: argoproj.io/v2.12.0-rc3
kind: Application
metadata:
  name: kubescape
  namespace: argocd # change to the argocd namespace
spec:
  destination:
    name: ''
    namespace: kubescape
    server: 'https://kubernetes.default.svc' # change to your server
  source:
    path: charts/kubescape-operator
    repoURL: 'https://github.com/kubescape/helm-charts'
    targetRevision: HEAD
    helm:
      valuesObject:
        certificates:
          strategy: hook # Important - prevents ArgoCD drift!
        clusterName: '' # add cluster name
        server: '' # add Kubescape-compatible backend service URL
        # imagePullSecrets: "" # reference to existing secret in same namespace
        # credentials:
        #   cloudSecret: "" # reference to existing secret in same namespace, contains `account` & `accessKey`
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    automated:
      prune: false
      selfHeal: true
