{{- $components := fromYaml (include "components" .) }}
{{- if and $components.operator.enabled (eq .Values.capabilities.admissionController "enable") (eq (include "kubescape.certificates.strategy" .) "template") }}
{{- $certData := fromYaml (include "kubescape-admission.certificateData" .) }}
{{- $ca := $certData.ca -}}
{{- $cert := $certData.cert -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubescape-admission.caSecretName" . }}
  namespace: {{ .Values.ksNamespace }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
    "helm.sh/resource-policy": keep
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.operator.name "tier" .Values.global.namespaceTier) | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.key: {{ $ca.Key | b64enc }}
  tls.crt: {{ $ca.Cert | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubescape-admission.secretName" . }}
  namespace: {{ .Values.ksNamespace }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" (include "kubescape-admission.name" .) "tier" .Values.global.namespaceTier) | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
{{- end }}
