apiVersion: v2
name: armosec-kubescape-operator
description: Kubescape is an E2E Kubernetes cluster security platform
type: application
version: 1.30.6+private.1
appVersion: 1.30.6+private.1

dependencies:
  - name: kubescape-operator
    version: 1.30.6
    repository: "file://../kubescape-operator"