apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustersecurityexceptions.kubescape.io
spec:
  group: kubescape.io
  names:
    plural: clustersecurityexceptions
    singular: clustersecurityexception
    kind: ClusterSecurityException
    shortNames:
      - cse
  scope: Cluster
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              properties:
                author:
                  type: string
                reason:
                  type: string
                expiresAt:
                  type: string
                  format: date-time
                match:
                  type: object
                  properties:
                    namespaceSelector:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    objectSelector:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    resources:
                      type: array
                      items:
                        type: object
                        required:
                          - kind
                        properties:
                          apiGroup:
                            type: string
                          kind:
                            type: string
                          name:
                            type: string
                    images:
                      type: array
                      items:
                        type: string
                vulnerabilities:
                  type: array
                  items:
                    type: object
                    required:
                      - vulnerability
                      - status
                    properties:
                      vulnerability:
                        type: object
                        required:
                          - id
                        properties:
                          id:
                            type: string
                          aliases:
                            type: array
                            items:
                              type: string
                      status:
                        type: string
                        enum:
                          - not_affected
                          - fixed
                          - under_investigation
                      justification:
                        type: string
                        enum:
                          - component_not_present
                          - vulnerable_code_not_present
                          - vulnerable_code_not_in_execute_path
                          - vulnerable_code_cannot_be_controlled_by_adversary
                          - inline_mitigations_already_exist
                      impactStatement:
                        type: string
                      expiredOnFix:
                        type: boolean
                posture:
                  type: array
                  items:
                    type: object
                    required:
                      - controlID
                      - action
                    properties:
                      controlID:
                        type: string
                      frameworkName:
                        type: string
                      action:
                        type: string
                        enum:
                          - ignore
                          - alert_only
            status:
              type: object
      additionalPrinterColumns:
        - name: Reason
          type: string
          jsonPath: .spec.reason
        - name: Expires
          type: string
          jsonPath: .spec.expiresAt
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
